version: '2.1'
services:

    unbound-openemail:
      image: openemail/unbound:1.6
      build: ./data/Dockerfiles/unbound
      command: /usr/sbin/unbound
      environment:
        - TZ=${TZ}
      volumes:
        - ./data/conf/unbound/unbound.conf:/etc/unbound/unbound.conf:ro
      restart: always
      tty: true
      networks:
        openemail-network:
          ipv4_address: ${IPV4_NETWORK:-172.22.1}.254
          aliases:
            - unbound

    mysql-openemail:
      image: mariadb:10.2
      volumes:
        - mysql-vol-1:/var/lib/mysql/
        - mysql-socket-vol-1:/var/run/mysqld/
        - ./data/conf/mysql/:/etc/mysql/conf.d/:ro
      environment:
        - TZ=${TZ}
        - MYSQL_ROOT_PASSWORD=${DBROOT}
        - MYSQL_DATABASE=${DBNAME}
        - MYSQL_USER=${DBUSER}
        - MYSQL_PASSWORD=${DBPASS}
      restart: always
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      ports:
        - "${SQL_PORT:-127.0.0.1:13306}:3306"
      networks:
        openemail-network:
          aliases:
            - mysql

    redis-openemail:
      image: redis:5-alpine
      volumes:
        - redis-vol-1:/data/
      restart: always
      environment:
        - TZ=${TZ}
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      networks:
        openemail-network:
          ipv4_address: ${IPV4_NETWORK:-172.22.1}.249
          aliases:
            - redis
            - redis-mailcow

    clamd-openemail:
      image: openemail/clamd:1.22
      build: ./data/Dockerfiles/clamd
      restart: always
      environment:
        - TZ=${TZ}
        - SKIP_CLAMD=${SKIP_CLAMD:-n}
      volumes:
        - ./data/conf/clamav/:/etc/clamav/
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      networks:
        openemail-network:
          aliases:
            - clamd

    rspamd-openemail:
      image: openemail/rspamd:1.34
      build: ./data/Dockerfiles/rspamd
      stop_grace_period: 30s
      depends_on:
        - nginx-openemail
      environment:
        - TZ=${TZ}
      volumes:
        - ./data/conf/rspamd/custom/:/etc/rspamd/custom
        - ./data/conf/rspamd/override.d/:/etc/rspamd/override.d
        - ./data/conf/rspamd/local.d/:/etc/rspamd/local.d
        - ./data/conf/rspamd/lua/:/etc/rspamd/lua/:ro
        - rspamd-vol-1:/var/lib/rspamd
      restart: always
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      hostname: rspamd
      networks:
        openemail-network:
          aliases:
            - rspamd

    php-fpm-openemail:
      image: openemail/phpfpm:1.34
      build: ./data/Dockerfiles/phpfpm
      command: "php-fpm -d date.timezone=${TZ} -d expose_php=0"
      depends_on:
        - redis-openemail
      volumes:
        - ./data/web:/web:rw
        - ./data/conf/rspamd/dynmaps:/dynmaps:ro
        - rspamd-vol-1:/var/lib/rspamd
        - mysql-socket-vol-1:/var/run/mysqld/
        - ./data/conf/sogo/:/etc/sogo/
        - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro
        - ./data/conf/phpfpm/php-fpm.d/pools.conf:/usr/local/etc/php-fpm.d/z-pools.conf
        - ./data/conf/phpfpm/php-conf.d/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
        - ./data/conf/phpfpm/php-conf.d/upload.ini:/usr/local/etc/php/conf.d/upload.ini
        - ./data/conf/phpfpm/php-conf.d/other.ini:/usr/local/etc/php/conf.d/zzz-other.ini
        - ./data/assets/templates:/tpls
      environment:
        - LOG_LINES=${LOG_LINES:-9999}
        - TZ=${TZ}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - OPENEMAIL_HOSTNAME=${OPENEMAIL_HOSTNAME}
        - IMAP_PORT=${IMAP_PORT:-143}
        - IMAPS_PORT=${IMAPS_PORT:-993}
        - POP_PORT=${POP_PORT:-110}
        - POPS_PORT=${POPS_PORT:-995}
        - SIEVE_PORT=${SIEVE_PORT:-4190}
        - SUBMISSION_PORT=${SUBMISSION_PORT:-587}
        - SMTPS_PORT=${SMTPS_PORT:-465}
        - SMTP_PORT=${SMTP_PORT:-25}
        - API_KEY=${API_KEY:-invalid}
        - API_ALLOW_FROM=${API_ALLOW_FROM:-invalid}
        - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-openemail-1.0}
        - SKIP_SOLR=${SKIP_SOLR:-y}
      restart: always
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      networks:
        openemail-network:
          aliases:
            - phpfpm

    sogo-openemail:
      image: openemail/sogo:1.52
      build: ./data/Dockerfiles/sogo
      environment:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - TZ=${TZ}
        - LOG_LINES=${LOG_LINES:-9999}
        - OPENEMAIL_HOSTNAME=${OPENEMAIL_HOSTNAME}
        - ACL_ANYONE=${ACL_ANYONE:-disallow}
      volumes:
        - ./data/conf/sogo/:/etc/sogo/
        - ./data/web/inc/init_db.inc.php:/init_db.inc.php
        - ./data/conf/sogo/custom-sogo.js:/usr/lib/GNUstep/SOGo/WebServerResources/js/custom-sogo.js
        - mysql-socket-vol-1:/var/run/mysqld/
      restart: always
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      networks:
        openemail-network:
          ipv4_address: ${IPV4_NETWORK:-172.22.1}.248
          aliases:
            - sogo

    dovecot-openemail:
      image: openemail/dovecot:1.63
      build: ./data/Dockerfiles/dovecot
      cap_add:
        - NET_BIND_SERVICE
      volumes:
        - ./data/conf/dovecot:/usr/local/etc/dovecot
        - ./data/assets/ssl:/etc/ssl/mail/:ro
        - ./data/conf/sogo/:/etc/sogo/
        - vmail-vol-1:/var/vmail
        - vmail-attachments-vol-1:/var/attachments
        - crypt-vol-1:/mail_crypt/
        - ./data/conf/rspamd/custom/:/etc/rspamd/custom
        - ./data/assets/templates:/templates
        - rspamd-vol-1:/var/lib/rspamd
        - mysql-socket-vol-1:/var/run/mysqld/
      environment:
        - LOG_LINES=${LOG_LINES:-9999}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - TZ=${TZ}
        - MAILDIR_GC_TIME=${MAILDIR_GC_TIME:-1440}
        - ACL_ANYONE=${ACL_ANYONE:-disallow}
        - SKIP_SOLR=${SKIP_SOLR:-y}
      ports:
        - "${DOVEADM_PORT:-127.0.0.1:19991}:12345"
        - "${IMAP_PORT:-143}:143"
        - "${IMAPS_PORT:-993}:993"
        - "${POP_PORT:-110}:110"
        - "${POPS_PORT:-995}:995"
        - "${SIEVE_PORT:-4190}:4190"
      restart: always
      tty: true
      ulimits:
        nproc: 65535
        nofile:
          soft: 20000
          hard: 40000
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      hostname: ${OPENEMAIL_HOSTNAME}
      networks:
        openemail-network:
          aliases:
            - dovecot

    postfix-openemail:
      image: openemail/postfix:1.29
      build: ./data/Dockerfiles/postfix
      volumes:
        - ./data/conf/postfix:/opt/postfix/conf
        - ./data/assets/ssl:/etc/ssl/mail/:ro
        - postfix-vol-1:/var/spool/postfix
        - crypt-vol-1:/var/lib/zeyple
        - rspamd-vol-1:/var/lib/rspamd
        - mysql-socket-vol-1:/var/run/mysqld/
      environment:
        - LOG_LINES=${LOG_LINES:-9999}
        - TZ=${TZ}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
      cap_add:
        - NET_BIND_SERVICE
      ports:
        - "${SMTP_PORT:-25}:25"
        - "${SMTPS_PORT:-465}:465"
        - "${SUBMISSION_PORT:-587}:587"
      restart: always
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      hostname: ${OPENEMAIL_HOSTNAME}
      networks:
        openemail-network:
          aliases:
            - postfix
            - postfix-dovecot

    memcached-openemail:
      image: memcached:alpine
      restart: always
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      networks:
        openemail-network:
          aliases:
            - memcached

    nginx-openemail:
      depends_on:
        - sogo-openemail
        - php-fpm-openemail
        - redis-openemail
      image: nginx:mainline-alpine
      command: /bin/sh -c "envsubst < /etc/nginx/conf.d/templates/listen_plain.template > /etc/nginx/conf.d/listen_plain.active &&
        envsubst < /etc/nginx/conf.d/templates/listen_ssl.template > /etc/nginx/conf.d/listen_ssl.active &&
        envsubst < /etc/nginx/conf.d/templates/server_name.template > /etc/nginx/conf.d/server_name.active &&
        envsubst < /etc/nginx/conf.d/templates/sogo.template > /etc/nginx/conf.d/sogo.active &&
        envsubst < /etc/nginx/conf.d/templates/sogo_eas.template > /etc/nginx/conf.d/sogo_eas.active &&
        nginx -qt &&
        until ping phpfpm -c1 > /dev/null; do sleep 1; done &&
        until ping sogo -c1 > /dev/null; do sleep 1; done &&
        until ping redis -c1 > /dev/null; do sleep 1; done &&
        until ping rspamd -c1 > /dev/null; do sleep 1; done &&
        exec nginx -g 'daemon off;'"
      environment:
        - VIRTUAL_HOST=admin.openemail.io
        - VIRTUAL_NETWORK=nginx-proxy
        - LETSENCRYPT_HOST=admin.openemail.io
        - LETSENCRYPT_EMAIL=devops@openemail.io
        - HTTPS_PORT=${HTTPS_PORT:-443}
        - HTTP_PORT=${HTTP_PORT:-80}
        - OPENEMAIL_HOSTNAME=${OPENEMAIL_HOSTNAME}
        - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
        - TZ=${TZ}
      volumes:
        - ./data/web:/web:ro
        - ./data/conf/rspamd/dynmaps:/dynmaps:ro
        - ./data/assets/ssl/:/etc/ssl/mail/:ro
        - ./data/conf/nginx/:/etc/nginx/conf.d/:rw
        - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro
      volumes_from:
        - sogo-openemail
      ports:
        - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
        - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
      restart: always
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      networks:
        openemail-network:
          aliases:
            - nginx
        proxy-tier:
      
    acme-openemail:
      depends_on:
        - nginx-openemail
      image: openemail/acme:1.48
      build: ./data/Dockerfiles/acme
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      environment:
        - LOG_LINES=${LOG_LINES:-9999}
        - ADDITIONAL_SAN=${ADDITIONAL_SAN}
        - OPENEMAIL_HOSTNAME=${OPENEMAIL_HOSTNAME}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - SKIP_LETS_ENCRYPT=${SKIP_LETS_ENCRYPT:-n}
        - SKIP_IP_CHECK=${SKIP_IP_CHECK:-n}
        - LE_STAGING=${LE_STAGING:-n}
        - TZ=${TZ}
      volumes:
        - ./data/web/.well-known/acme-challenge:/var/www/acme:rw
        - ./data/assets/ssl:/var/lib/acme/:rw
        - ./data/assets/ssl-example:/var/lib/ssl-example/:ro
        - mysql-socket-vol-1:/var/run/mysqld/
      restart: always
      networks:
        openemail-network:
          aliases:
            - acme
    openldap-fusiondirectory-openemail:
      image: tiredofit/openldap-fusiondirectory
      environment:
        - HOSTNAME=${HOSTNAME}
        - BACKEND=${BACKEND}
        - LOG_LEVEL=${LOG_LEVEL}
        - DOMAIN=${DOMAIN}
        - ADMIN_PASS=${ADMIN_PASS}
        - CONFIG_PASS=${CONFIG_PASS}
        - FUSIONDIRECTORY_ADMIN_USER=${FUSIONDIRECTORY_ADMIN_USER}
        - FUSIONDIRECTORY_ADMIN_PASS=${FUSIONDIRECTORY_ADMIN_PASS}
        - ORGANIZATION=${ORGANIZATION}
        - BASE_DN=${BASE_DN}
        - ENABLE_READONLY_USER=${ENABLE_READONLY_USER}
        - READONLY_USER_USER=${READONLY_USER_USER}
        - READONLY_USER_PASS=${READONLY_USER_PASS}
        - ENABLE_TLS=${ENABLE_TLS}
        - TLS_CRT_FILENAME=${TLS_CRT_FILENAME}
        - TLS_KEY_FILENAME=${TLS_KEY_FILENAME}
        - TLS_CA_CRT_FILENAME=${TLS_CA_CRT_FILENAME}
        - TLS_ENFORCE=${TLS_ENFORCE}
        - TLS_CIPHER_SUITE=${TLS_CIPHER_SUITE}
        - TLS_VERIFY_CLIENT=${TLS_VERIFY_CLIENT}
        - SSL_HELPER_PREFIX=${SSL_HELPER_PREFIX}
        - ENABLE_REPLICATION=${ENABLE_REPLICATION}
        - REPLICATION_CONFIG_SYNCPROV=${REPLICATION_CONFIG_SYNCPROV}
        - REPLICATION_DB_SYNCPROV=${REPLICATION_DB_SYNCPROV}
        - REPLICATION_HOSTS=${REPLICATION_HOSTS}
        - REMOVE_CONFIG_AFTER_SETUP=${REMOVE_CONFIG_AFTER_SETUP}
        - BACKUP_CONFIG_CRON_PERIOD=0 4 * * *
        - BACKUP_DATA_CRON_PERIOD=0 4 * * *
        - BACKUP_TTL=15
        - ZABBIX_HOSTNAME=openldap-fusiondirectory
      volumes:
        - ./ldap/backup:/data/backup
        - ./ldap/data:/var/lib/openldap
        - ./ldap/config:/etc/openldap/slapd.d
        - ./data/assets/ssl/:/assets/slapd/certs
      ports:
        - 389:389
        - 636:636
      restart: always
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      hostname: ${OPENEMAIL_HOSTNAME}
      networks:
        openemail-network:
          aliases: 
            - openldap-fusiondirectory

    fusiondirectory-openemail:
      image: tiredofit/fusiondirectory
      environment:
        - VIRTUAL_HOST=fd.openemail.io
        - VIRTUAL_NETWORK=nginx-proxy
        - LETSENCRYPT_HOST=fd.openemail.io
        - LETSENCRYPT_EMAIL=devops@openemail.io
        - PLUGIN_ALIAS=TRUE
        - PLUGIN_APPLICATIONS=TRUE
        - PLUGIN_ARGONAUT=TRUE
        - PLUGIN_AUDIT=TRUE
        - PLUGIN_AUTOFS=TRUE
        - PLUGIN_CERTIFICATES=TRUE
        - PLUGIN_COMMUNITY=TRUE
        - PLUGIN_CYRUS=TRUE
        - PLUGIN_DEBCONF=TRUE
        - PLUGIN_DEVELOPERS=TRUE
        - PLUGIN_DHCP=TRUE
        - PLUGIN_DNS=TRUE
        - PLUGIN_DOVECOT=TRUE
        - PLUGIN_DSA=TRUE
        - PLUGIN_EJBCA=TRUE
        - PLUGIN_FAI=TRUE
        - PLUGIN_FREERADIUS=TRUE
        - PLUGIN_FUSIONINVENTORY=TRUE
        - PLUGIN_GPG=TRUE
        - PLUGIN_IPMI=TRUE
        - PLUGIN_LDAPDUMP=TRUE
        - PLUGIN_LDAPMANAGER=TRUE
        - PLUGIN_MAIL=TRUE
        - PLUGIN_MIXEDGROUPS=TRUE
        - PLUGIN_NAGIOS=TRUE
        - PLUGIN_NETGROUPS=TRUE
        - PLUGIN_NEWSLETTER=TRUE
        - PLUGIN_OPSI=TRUE
        - PLUGIN_PERSONAL=TRUE
        - PLUGIN_POSIX=TRUE
        - PLUGIN_POSTFIX=TRUE
        - PLUGIN_PPOLICY=TRUE
        - PLUGIN_PUPPET=TRUE
        - PLUGIN_PUREFTPD=TRUE
        - PLUGIN_QUOTA=TRUE
        - PLUGIN_RENATER_PARTAGE=TRUE
        - PLUGIN_REPOSITORY=TRUE
        - PLUGIN_SAMBA=TRUE
        - PLUGIN_SOGO=TRUE
        - PLUGIN_SPAMASSASSIN=TRUE
        - PLUGIN_SQUID=TRUE
        - PLUGIN_SSH=TRUE
        - PLUGIN_SUBCONTRACTING=TRUE
        - PLUGIN_SUDO=TRUE
        - PLUGIN_SUPANN=TRUE
        - PLUGIN_SYMPA=TRUE
        - PLUGIN_SYSTEMS=TRUE
        - PLUGIN_USER_REMINDER=TRUE
        - PLUGIN_WEBLINK=TRUE
        - LDAP1_HOST=openldap-fusiondirectory
        - LDAP1_BASE_DN=${BASE_DN}
        - LDAP1_ADMIN_DN=${LDAP1_BASE_DN}
        - LDAP1_ADMIN_PASS=${LDAP1_ADMIN_PASS}
        - LDAP1_NAME=${LDAP1_NAME}
        - ZABBIX_HOSTNAME=fusiondirectory
      volumes:
        - ./fusiond/config/fd:/etc/fusiondirectory
        - ./fusiond/logs:/www/logs
        - ./fusiond/custom:/assets/fusiondirectory
        - ./fusiond/plugins-custom:/assets/plugins-custom
        - ./data/assets/ssl/:/assets/ssl/certs
      ports:
        - "${FDUI_PORT:-0.0.0.0:1080}:80"
      restart: always
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      networks:
        openemail-network:
          aliases: 
            - fusiondirectory
        proxy-tier:
        
    netfilter-openemail:
      image: openemail/netfilter:1.22
      build: ./data/Dockerfiles/netfilter
      stop_grace_period: 30s
      depends_on:
        - dovecot-openemail
        - postfix-openemail
        - sogo-openemail
        - php-fpm-openemail
        - redis-openemail
        - openldap-fusiondirectory-openemail
        - fusiondirectory-openemail
      restart: always
      privileged: true
      environment:
        - TZ=${TZ}
        - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
        - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
        - SNAT_TO_SOURCE=${SNAT_TO_SOURCE:-n}
        - SNAT6_TO_SOURCE=${SNAT6_TO_SOURCE:-n}
      network_mode: "host"
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      volumes:
        - /lib/modules:/lib/modules:ro

    watchdog-openemail:
      image: openemail/watchdog:1.35
      # Debug
      #command: /watchdog.sh
      build: ./data/Dockerfiles/watchdog
      oom_kill_disable: true
      volumes:
        - rspamd-vol-1:/var/lib/rspamd
        - mysql-socket-vol-1:/var/run/mysqld/
      restart: always
      environment:
        - LOG_LINES=${LOG_LINES:-9999}
        - TZ=${TZ}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - USE_WATCHDOG=${USE_WATCHDOG:-n}
        - WATCHDOG_NOTIFY_EMAIL=${WATCHDOG_NOTIFY_EMAIL}
        - OPENEMAIL_HOSTNAME=${OPENEMAIL_HOSTNAME}
        - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
        - IP_BY_DOCKER_API=${IP_BY_DOCKER_API:-0}
        - CHECK_UNBOUND=${CHECK_UNBOUND:-1}
        - SKIP_CLAMD=${SKIP_CLAMD:-n}
        - SKIP_LETS_ENCRYPT=${SKIP_LETS_ENCRYPT:-n}
        - HTTPS_PORT=${HTTPS_PORT:-443}
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      networks:
        openemail-network:
          aliases:
            - watchdog

    dockerapi-openemail:
      image: openemail/dockerapi:1.26
      restart: always
      build: ./data/Dockerfiles/dockerapi
      oom_kill_disable: true
      environment:
        - DBROOT=${DBROOT}
        - TZ=${TZ}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./data/conf/rspamd/override.d/worker-controller-password.inc:/access.inc:rw
      networks:
        openemail-network:
          aliases:
            - dockerapi

    solr-openemail:
      image: openemail/solr:1.2
      build: ./data/Dockerfiles/solr
      restart: always
      volumes:
        - solr-vol-1:/opt/solr/server/solr/dovecot/data
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      environment:
        - TZ=${TZ}
        - SOLR_HEAP=${SOLR_HEAP:-1024}
        - SKIP_SOLR=${SKIP_SOLR:-y}
      networks:
        openemail-network:
          aliases:
            - solr

    ipv6nat-openemail:
      depends_on:
        - unbound-openemail
        - mysql-openemail
        - redis-openemail
        - clamd-openemail
        - rspamd-openemail
        - php-fpm-openemail
        - sogo-openemail
        - dovecot-openemail
        - postfix-openemail
        - memcached-openemail
        - nginx-openemail
        - acme-openemail
        - netfilter-openemail
        - watchdog-openemail
        - dockerapi-openemail
        - solr-openemail
      image: robbertkl/ipv6nat
      restart: always
      privileged: true
      network_mode: "host"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /lib/modules:/lib/modules:ro

networks:
  openemail-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
        - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
  proxy-tier:
    external:
      name: nginx-proxy

volumes:
  # Storage for email files
  vmail-vol-1:
  # Storage for attachments (deduplicated)
  vmail-attachments-vol-1:
  mysql-vol-1:
  mysql-socket-vol-1:
  redis-vol-1:
  rspamd-vol-1:
  solr-vol-1:
  postfix-vol-1:
  crypt-vol-1:
