version: '2.1'
services:

    php-fpm-openemail:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    sogo-openemail:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    dovecot-openemail:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    postfix-openemail:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    acme-openemail:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    watchdog-openemail:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    mysql-openemail:
      image: alpine:3.8
      command: /bin/true
      restart: "no"
